### ISSUE TITLE
Include more columns on collapsed view

### ISSUE THREAD

**Issue by chros73** [chros73/rtorrent-ps#1]
Include more columns on collapsed view, like it was mentioned here https://github.com/pyroscope/rtorrent-ps/issues/5 , with the following modifications:
* add a column after Priority for Throttle ( Ø ) : none = global throttle, ∞ = NULL throttle, otherwise the first letter of the throttle name
* add a column after the last scrape info for Number of connected peers ( ↻ )
* modify upload rate column to display the approximate time since last active state only if there's no upload rate at the moment, change its header to ( ⌚ ≀∆ ); also color time with a single color (queued color)
* add a column after upload rate/last active time for Uploaded data size (⊼), use 6 chars wide format and include a dot when uploaded data size is 0

**Comment by matsah** [comment]
Maybe you would want to center the icon like "Data size":
![ps](https://cloud.githubusercontent.com/assets/15032426/14919488/627dcce8-0e29-11e6-816d-0bdb9226cabe.png)

**Comment by chros73** [comment]
That column can be 6 chars long, that means you can really center it. If you have a value like 897.0M then the header is almost in the center.

**Comment by chros73** [comment]
Done. Thanks for mentioning!
