### ISSUE TITLE
add utp support

### ISSUE THREAD

**Issue by colinhd8** [chros73/rtorrent-ps#59]
Great project(rtorrent-ps and rtorrent). I really love them. Thanks.
But compare to other bt clients(utorrent, qbittorrent,deluge), rtorent's download speed is slower(upload speed is fine), and hard to connect to peers.(for example, on the same network and same torrent, ut can connect to 100+ peers, rt only 20~40, confirm that config is ok). 
I think the one reason is that rtorrent doesn't support utp.
So, chros73, if you have time, could you please add the utp support feature to rtorrent(There is already a utp repository.https://github.com/bittorrent/libutp)?

Thank you so much.

**Comment by chros73** [comment]
> Great project(rtorrent-ps and rtorrent). I really love them. Thanks.

I'm glad to hear that, but majority of the work thanks to pyroscope.

> if you have time, could you please add the utp support

I'm sorry to tell you this, but I don't have time for that. :( I know, that you asked the same question in the libtorrent project, let's hope that somebody will implement it soon. :)

**Comment by colinhd8** [comment]
>  I'm glad to hear that, but majority of the work thanks to pyroscope.



Yes, also thanks to pyroscope.


> I'm sorry to tell you this, but I don't have time for that. :( I know, that you asked the same question in the libtorrent project, let's hope that somebody will implement it soon. :)



OK, let's hope together.:)
