### ISSUE TITLE
self url in build.sh

### ISSUE THREAD

**Issue by colinhd8** [chros73/rtorrent-ps#60]
The self url in the build.sh is https://github.com/pyroscope/rtorrent-ps.git. And how it use the patches from this repo.

**Comment by chros73** [comment]
Good catch, thanks, fixed.
Although it didn't effect compiling if you do it according to the [instruction](https://github.com/chros73/rtorrent-ps/blob/master/docs/DebianInstallFromSourceTheEasyWay.rst#compiling-rtorrent-ps-ch-from-source).

**Comment by colinhd8** [comment]
Thanks for fix.
Yes, according to the instruction it will use the right patches, but if you just download the build.sh itself and use the command "./build.sh all" then it will use the patches from https://github.com/pyroscope/rtorrent-ps.git.
