### ISSUE TITLE
Update to current head fork

### ISSUE THREAD

**Issue by chros73** [chros73/rtorrent-ps#75]
Update to current head fork:
- include `lt-ps` patches in build script
- add new patches by pyroscope
  - lt-ps_0.9.7_01-log_open_file-reopen_all.patch
  - ps-event-view_all.patch
  - ps-fix-double-slash-319_all.patch
  - ps-handle-sighup-578_all.patch
  - ps-view-filter-by_all.patch
- update completely `command_pyroscope.cc` and mod it to be able to compile with git version
- update `ui_pyroscope.cc`:
  - add [UI: tracker alias mappings](https://github.com/pyroscope/rtorrent-ps/commit/a560233217a0d1eef6919dee36455680dd60dcbf#diff-afef18968b3416723328ee9170b32a34)
  - add [convert.human_size command](https://github.com/pyroscope/rtorrent-ps/commit/818a72eaa17ded9bad003d72b20e522059eac508)
  - add [convert.magnitude command](https://github.com/pyroscope/rtorrent-ps/commit/23a9f37d8566c0f9f8a9890acac78fe4d21a269d)
  - add [u8_chop function](https://github.com/pyroscope/rtorrent-ps/commit/41c1d6247769939d5f4d0321abc866b090e2f10a) (we don't use it for now)
  - do not modify column rendering for now
    - [UI: Added canvas customization](https://github.com/pyroscope/rtorrent-ps/commit/462a65eddf8743b43b25924fe8da6c16c0a9c292) and related commits

**Comment by colinhd8** [comment]
Good news. I can't wait to see it. Hope it will be there soon.Thank you.

**Comment by chros73** [comment]
[New version](https://github.com/chros73/rtorrent-ps/releases) is out: we only support git version. :)
