### ISSUE TITLE
rtorrent become to unusable when set out rang ui color

### ISSUE THREAD

**Issue by colinhd8** [chros73/rtorrent-ps#76]
for example: when call the command "ui.color.footer.set="bright cyan on 2412"", rtorrent will display the error message:Input failed: bright cyan on 2412: your terminal only supports 256 colors.

After that, rtorrent will become to unusable.

I know this is not a big problem, but i hope it can be fixed. Thanks.

**Comment by chros73** [comment]
:) How did you manage to do this?
I'll take a look, if it's easily fixable then I'll do it if not I'll leave it.

**Comment by chros73** [comment]
Fixed. Can you give it a try?

**Comment by colinhd8** [comment]
Thanks. It seems that it's be fixed partially. After the command, the footer bar lose it's color.

**Comment by chros73** [comment]
> It seems that it's be fixed partially. After the command, the footer bar lose it's color.

Strange, not for me. E.g. hit `CTRL+X` and :
- `ui.color.footer.set="bright cyan on 2412"`
- `ui.color.complete.set = "411"`

Footer remains the same and complete color isn't changed either.
We receive the following message: Input failed: 411: your terminal only supports 256 colors.

Anyway, at least it works fine afterwards.

Note: I used it in tmux with [this config](https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.tmux.conf).

**Comment by chros73** [comment]
> After the command,

Which command? :)

**Comment by colinhd8** [comment]
> Which command? :)
for example: CTRL+X and :
ui.color.footer.set="bright cyan on 2412"

I'll attach some hardcopy later.

**Comment by colinhd8** [comment]
before execute the command:
![before](https://cloud.githubusercontent.com/assets/5259758/25853764/752362b4-3500-11e7-9a6a-70bfebc39e9d.PNG)


 after execute the command:
![after](https://cloud.githubusercontent.com/assets/5259758/25853775/7ae94330-3500-11e7-8973-c898def59348.PNG)

**Comment by chros73** [comment]
Sorry about this, you are right (I don't know what I tested :) ).
Upon a bad entry the previous format is cleared and nothing is applied.
Anyways it's all cosmetics, the major issue was that canvas could be freezed.

And if you'll come up a nice theme like [these](https://github.com/chros73/rtorrent-ps_setup/tree/master/ubuntu-14.04/home/chros73/.pyroscope) then don't hesitate to share it :) Cheers

**Comment by colinhd8** [comment]
Yes, I will. It's my pleasure.

Anyway thanks for fix the major issue.
