### ISSUE TITLE
Support only git version (not old versions)

### ISSUE THREAD

**Issue by chros73** [chros73/rtorrent-ps#78]
Remove support (patches) for version `0.9.6` and earlier:
- git version is stable
- based on slightly different codebase
- includes lot of fixes, enhancements
  - udp communication
  - ipv6 support

Todo:
- remove old patches
- rename remaining patches.
- remove also the unused `moin/plugin/parser/rc.py`
- update gitignore

If earlier version(s) is required - for whatever reason -, use tag [1.4.6-0.9.6](https://github.com/chros73/rtorrent-ps/releases).

**Comment by colinhd8** [comment]
> udp communication
Does it mean that rtorrent supports utp now?

**Comment by chros73** [comment]
No, it was about UDP in general.
